# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
